project_id = "pcjpajdrqanbffiktxvy"

[functions.sync-design-docs]
verify_jwt = false

[functions.invite-collaborator]
verify_jwt = false

[functions.commit-to-gitlab]
verify_jwt = false

[functions.gitlab-versions]
verify_jwt = false
